export const mediaTaxonomy: Record<string, string[]> = {
  Drawing: [
    "Graphite (pencil, powder, mechanical)",
    "Charcoal (vine, compressed)",
    "Chalk (red/white/black, sanguine)",
    "Conté (sticks, pencils)",
    "Pastel (soft, hard, oil, pan)",
    "Ink (India, sumi, iron-gall; brush/pen; wash)",
    "Markers (alcohol/water/paint)",
    "Silverpoint/metalpoint",
    "Colored pencil (wax/oil/water-soluble)",
  ],
  Painting: [
    "Oil (alla prima, glazing, impasto, grisaille)",
    "Acrylic (impasto, pouring, airbrush, glazing)",
    "Watercolor (transparent, wet-on-wet, drybrush)",
    "Gouache (opaque watercolor)",
    "Tempera (egg tempera, casein)",
    "Encaustic (hot wax)",
    "Fresco (buon fresco, fresco secco)",
    "Ink painting (sumi-e)",
    "Spray/Aerosol (stencil, freehand)",
    "Vitreous enamel",
  ],
  Printmaking: [
    "Relief (woodcut, linocut, wood engraving)",
    "Intaglio (engraving, etching, drypoint, aquint, mezzotint, photogravure)",
    "Planographic (lithography)",
    "Stencil (screenprint/serigraph, pochoir)",
    "Monotype/monoprint",
    "Collagraph",
    "Digital print (inkjet/pigment/giclée, UV flatbed)",
    "Risograph",
  ],
  Sculpture: [
    "Stone (carving)",
    "Wood (carving, turning)",
    "Metal (lost-wax bronze, sand casting, forging, fabrication/welding)",
    "Clay/Terracotta (modeling, casting)",
    "Plaster (modeling, molds)",
    "Resin & plastics (casting, vacuum forming, 3D printing)",
    "Found-object/assemblage",
    "Kinetic",
    "Soft sculpture",
  ],
  "Ceramics & Glass": [
    "Ceramics (earthenware, stoneware, porcelain, raku, terra sigillata; wheel-thrown, handbuilt/coil/slab, slip-cast; sgraffito, inlay/mishima; glaze/underglaze)",
    "Glass (blown, cast, kiln-formed/fused, stained, lampworking)",
  ],
  "Textile / Fiber": [
    "Weaving (tapestry)",
    "Knitting",
    "Crochet",
    "Embroidery (including culturally specific forms like tatreez)",
    "Quilting (patchwork, appliqué)",
    "Felting (wet/needle/nuno)",
    "Macramé",
    "Resist dyeing (batik, shibori, tie-dye, ikat)",
  ],
  Photography: [
    "Analog: daguerreotype, ambrotype, tintype/ferrotype",
    "Digital: pigment inkjet",
  ],
  "Time-based Media (Film/Video/Animation/Sound)": [
    "Film (8mm/Super 8, 16mm, 35mm)",
    "Video (single-channel, multichannel installation)",
  ],
  "Digital / Computational / New Media": [
    "Digital painting (raster/vector)",
    "Generative/code art (algorithmic, Processing/p5.js)",
  ],
  "Book & Text Arts": ["Artist’s books, zines, altered books", "Letterpress"],
  "Street / Public / Environmental": [
    "Street art (graffiti, stencil, murals)",
    "Public art (monumental sculpture)",
  ],
  "Mixed / Hybrid & Non-traditional / Experimental": [
    "Collage (paper/photo/digital)",
    "Assemblage (found materials)",
  ],
};